ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mfa_totp_secret TEXT,
    ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mfa_secret_issued_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS mfa_confirmed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
