apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 555.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/operation-id: 8af09e74-ac5c-4cdb-aa6e-f04c3eaa5aae
    run.googleapis.com/urls: '["https://accounts-svc-plus-266500572462.asia-northeast1.run.app","https://accounts-svc-plus-pztvwzbmpq-an.a.run.app"]'
    serving.knative.dev/creator: haitaopanhq@gmail.com
    serving.knative.dev/lastModifier: 266500572462-compute@developer.gserviceaccount.com
  creationTimestamp: '2026-01-21T07:30:18.219865Z'
  generation: 156
  labels:
    cloud.googleapis.com/location: asia-northeast1
    commit-sha: d00593cdbe210afcd2e9256f9b01eacc1dd5a82f
    gcb-build-id: 2dcbf48a-0089-481a-b5d1-a4a9b51d79f4
    gcb-trigger-id: f3a71b58-1099-464c-b93f-c02fc0096482
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: accounts-svc-plus
  namespace: '266500572462'
  resourceVersion: AAZKXDKq9Aw
  selfLink: /apis/serving.knative.dev/v1/namespaces/266500572462/services/accounts-svc-plus
  uid: 3da8f202-ba3b-45ac-ba10-cf8d7fe4e8bd
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 555.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: yjytsktqnu
        commit-sha: d00593cdbe210afcd2e9256f9b01eacc1dd5a82f
        gcb-build-id: 2dcbf48a-0089-481a-b5d1-a4a9b51d79f4
        gcb-trigger-id: f3a71b58-1099-464c-b93f-c02fc0096482
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: CONFIG_TEMPLATE
          value: /app/config/account.cloudrun.yaml
        - name: PGADMIN_PASSWORD
          value: admin_password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres-password
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: '15432'
        - name: DB_USER
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: DB_NAME
          value: account
        - name: INTERNAL_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: internal-service-token
        - name: SMTP_HOST
          value: smtp.qq.com
        - name: SMTP_PORT
          value: '587'
        - name: SMTP_FROM
          value: XControl Account <manbuzhe2009@qq.com>
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: smtp-password
        image: asia-northeast1-docker.pkg.dev/xzerolab-480008/cloud-run-source-deploy/accounts.svc.plus/accounts-svc-plus:d00593cdbe210afcd2e9256f9b01eacc1dd5a82f
        name: accounts-api
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      - command:
        - stunnel
        - /etc/stunnel/stunnel.conf
        image: dweomer/stunnel
        name: stunnel-sidecar
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/stunnel
          name: stunnel-conf-vol
      serviceAccountName: 266500572462-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - name: stunnel-conf-vol
        secret:
          items:
          - key: latest
            path: stunnel.conf
          secretName: stunnel-config
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://accounts-svc-plus-pztvwzbmpq-an.a.run.app
  conditions:
  - lastTransitionTime: '2026-02-09T04:01:47.774988Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-02-09T04:01:46.520578Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-02-09T04:01:47.745338Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: accounts-svc-plus-00144-225
  latestReadyRevisionName: accounts-svc-plus-00144-225
  observedGeneration: 156
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: accounts-svc-plus-00144-225
  url: https://accounts-svc-plus-pztvwzbmpq-an.a.run.app
